# Schema for the configuration files of the discussions module.

discussions_email.settings:
  type: config_object
  label: 'Discussions email settings'
  mapping:
    plugin_id:
      type: string
      label: 'Email plugin ID'
    filter_css_classes:
      type: string
      label: 'Filter email CSS classes'
    email_author:
      type: boolean
      label: 'Send email to author'
    process_bounces:
      type: boolean
      label: 'Process bounces'
    attachment_send_limit:
      type: string
      label: 'Attachment size send limit'
