block.settings.drulma_companion_bulma_navbar_with_branding:*:
  type: block_settings
  label: 'Bulma navbar with branding block'
  mapping:
    level:
      type: integer
      label: 'Starting level'
    depth:
      type: integer
      label: 'Maximum number of levels'
    navbar_color:
      type: string
      label: 'Navbar color'
    horizontally_centered:
      type: boolean
      label: 'Center navbar horizontally'
    navbar_start_display:
      type: boolean
      label: 'Display navbar start menu'
    end_menu:
      type: string
      label: 'Menu to display navbar at the end of the navbar'
    end_menu_level:
      type: integer
      label: 'Starting level'
    end_menu_depth:
      type: integer
      label: 'Maximum number of levels'
    use_site_logo:
      type: boolean
      label: 'Use site logo'
    use_site_name:
      type: boolean
      label: 'Use site name'
    use_site_slogan:
      type: boolean
      label: 'Use site slogan'
    site_name_size:
      type: string
      label: 'Size of the site name'
    site_slogan_size:
      type: string
      label: 'Size of the site slogan'

block.settings.drulma_companion_menu_tabs:*:
  type: block_settings
  label: 'Bulma menus as tabs'
  mapping:
    level:
      type: integer
      label: 'Starting level'
    depth:
      type: integer
      label: 'Maximum number of levels'
    horizontally_centered:
      type: boolean
      label: 'Center tabs horizontally'
    boxed:
      type: boolean
      label: 'Style tabs as boxes'
    toggle:
      type: boolean
      label: 'Style tabs as mutually exclusive'
    toggle_rounded:
      type: boolean
      label: 'Style tabs as mutually exclusive with round edges'
    fullwidth:
      type: boolean
      label: 'Make tabs occupy the whole width'
    size:
      type: string
      label: 'Size of the tabs'
    alignment:
      type: string
      label: 'Alignment of the tabs'

block.settings.drulma_companion_local_tasks_block:*:
  type: block_settings
  label: 'Bulma tabs'
  mapping:
    primary:
      type: boolean
      label: 'Whether primary tabs are shown'
    secondary:
      type: boolean
      label: 'Whether secondary tabs are shown'
    horizontally_centered:
      type: boolean
      label: 'Center tabs horizontally'
    fullwidth:
      type: boolean
      label: 'Make tabs occupy the whole width'

field.formatter.settings.drulma_entity_reference_label_tags:
  type: mapping
  label: Labels as Bulma tags formatter settings
  mapping:
    size:
      type: string
      label: Size
    color:
      type: string
      label: Color
    rounded:
      type: boolean
      label: Rounded
    inline:
      type: boolean
      label: Inline
