feadmin_test.dummy.*:
  type: config_object
  label: 'Front-End Administration module settings'
  mapping:
    dummy_label:
      type: label
      label: 'Dummy label'
    dummy_option:
      type: boolean
      label: 'Dummy option'
