core.entity_view_display.*.*.*.third_party.layout_builder_restrictions:
  type: layout_builder_restrictions.third_party_settings

layout_builder_restrictions.third_party_settings:
  type: mapping
  label: 'Per-view-mode Layout Builder Restrictions settings'
  mapping:
    allowed_blocks:
      type: sequence
      label: 'Allowed blocks by category'
      sequence:
        type: sequence
        label: 'Allowed blocks'
        sequence:
          type: string
          label: 'Block ID'
    allowed_layouts:
      type: sequence
      label: 'Allowed layouts by category'
      sequence:
        type: sequence
        label: 'Allowed layouts'
        sequence:
          type: string
          label: 'Layout ID'
