dat.dat_connection.*:
  type: config_entity
  label: 'Database connection entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    type:
      type: string
      label: 'Type'
    driver:
      type: string
      label: 'driver'
    server_name:
      type: string
      label: 'Server name'
    name:
      type: string
      label: 'Database name'
    host:
      type: string
      label: 'Host'
    port:
      type: integer
      label: 'Port'
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
    allowed_schemas:
      type: string
      label: 'Allowed Schemas'
    style:
      type: string
      label: 'Style file uri'
