services:
  config_pr.repo_controller_manager:
    class: Drupal\config_pr\RepoControllerManager
    tags:
      - { name: service_collector, tag: config_pr.repo_controller, call: addController }

  config_pr.repo_controller.github:
    class: Drupal\config_pr\RepoControllers\GithubController
    tags:
      - { name: config_pr.repo_controller }

  config_pr.repo_controller.github_enterprise:
    class: Drupal\config_pr\RepoControllers\GithubEnterpriseController
    tags:
      - { name: config_pr.repo_controller }
