name: Config Auto Export
type: module
description: Auto detects config changes and exports those to a configurable directory and optionally triggers a web hook.
core: 8.x
package: Configuration

dependencies:
  - 'yaml_editor'
