# Schema for the configuration file of the Yandex.Metrics Counter module.

yandex_metrics.settings:
  type: config_object
  label: 'Yandex.Metrics Counter settings'
  mapping:
    counter_code:
      type: string
      label: 'Counter code'
    visibility:
      type: mapping
      label: 'Visibility settings'
      mapping:
        path:
          type: mapping
          label: 'Page specific tracking settings'
          mapping:
            visibility:
              type: integer
              label: 'Add code to specific pages'
            pages:
              type: text
              label: 'Pages'
        role:
          type: mapping
          label: 'Role specific tracking settings'
          mapping:
            visibility:
              type: integer
              label: 'Add tracking for specific roles'
            roles:
              type: sequence
              label: 'Roles'
              sequence:
                type: string
                label: 'Role'
