share_everywhere.settings:
  type: config_object
  mapping:
    buttons:
      type: mapping
      mapping:
        facebook_like:
          type: mapping
          mapping:
            name:
              type: string
            enabled:
              type: integer
        facebook_share:
          type: share_everywhere.image_button
        twitter:
          type: share_everywhere.image_button
        googleplus:
          type: share_everywhere.image_button
        linkedin:
          type: share_everywhere.image_button
        messenger:
          type: share_everywhere.image_button
        viber:
          type: share_everywhere.image_button
        whatsapp:
          type: share_everywhere.image_button
    share_icon:
      type: mapping
      mapping:
        image:
          type: string
        alt:
          type: string
    title:
      type: string
    display_title:
      type: integer
    style:
      type: string
    include_css:
      type: integer
    include_js:
      type: integer
    collapsible:
      type: integer
    location:
      type: string
    alignment:
      type: string
    content_types:
      type: sequence
      sequence:
        type: string
    view_modes:
      type: sequence
      sequence:
        type: sequence
        sequence:
          type: string
    product_types:
      type: sequence
      sequence:
        type: string
    product_view_modes:
      type: sequence
      sequence:
        type: sequence
        sequence:
          type: string
    restricted_pages:
      type: mapping
      mapping:
        pages:
          type: string
        type:
          type: string
    weight:
      type: integer

share_everywhere.image_button:
  type: mapping
  mapping:
    name:
      type: string
    title:
      type: string
    enabled:
      type: integer
    image:
      type: string
