commerce_payment.commerce_payment_gateway.plugin.commerce_instamojo_payment:
  type: commerce_payment_gateway_configuration
  mappings:
    api_key:
      type: string
      label: 'Private API Key'
    auth_token:
      type: string
      label: 'Private Auth Token'
    salt:
      type: string
      label: 'Private Salt'
    order_prefix:
      type: string
      label: 'Order Prefix'
    send_email:
      type: boolean
      label: 'Send Email'
    allow_repeated_payments:
      type: boolean
      label: 'Allow Repeated Payments'
    watchdog_log:
      type: boolean
      label: 'Watchdog Log'
