tealiumiq_api.settings:
  type: config_object
  label: 'Tealium iQ API Settings'
  mapping:
    username:
      type: string
      label: 'Username'
    api_key:
      type: string
      label: 'API key'
    api_base_uri:
      type: string
      label: 'API Base Uri'
