agreement.agreement.*:
  type: config_entity
  label: 'Agreement'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Name'
    path:
      type: uri
      label: 'Path'
    settings:
      type: agreement_settings
      label: 'Settings'
    agreement:
      type: text
      label: 'Agreement text'
      translatable: true

agreement_settings:
  type: mapping
  label: 'Settings'
  mapping:
    frequency:
      type: integer
      label: 'Frequency'
    title:
      type: string
      label: 'Agreement Page Title'
      translatable: true
    checkbox:
      type: string
      label: 'Checkbox Text'
      translatable: true
    format:
      type: string
      label: 'Text format'
    submit:
      type: string
      label: 'Submit Text'
      translatable: true
    success:
      type: text
      label: 'Success Message'
      translatable: true
    revoked:
      type: text
      label: 'Revoked Message'
      translatable: true
    failure:
      type: text
      label: 'Failure Message'
      translatable: true
    destination:
      type: uri
      label: 'Destination'
    reset_date:
      type: integer
      label: 'Last Reset Date'
    visibility:
      type: mapping
      label: 'Visibility'
      mapping:
        settings:
          type: integer
          label: 'Visibility Settings'
        pages:
          type: sequence
          label: 'Pages'
          sequence:
            type: uri
    recipient:
      type: email
      label: 'Recipient Email'
      nullable: true
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        type: string
