spamicide.spamicide.*:
  type: config_entity
  label: spamicide
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
