content_entity_builder.content_type.*:
  type: config_entity
  label: 'Content type'
  mapping:
    id:
      type: string
    label:
      type: string
      label: 'Label'
    keys:
      type: mapping
      label: 'Entity keys'
    paths:
      type: mapping
      label: 'Entity paths'
    applied:
      type: boolean
      label: 'Is Applied'       
    basefields:
      type: sequence
      sequence:
        type: mapping
        mapping:
          id:
            type: string
          field_name:
            type: string
            label: 'Field name'
          label:
            type: string
            label: 'Field label'
          field_type:
            type: string
            label: 'Field type'         
          settings:
            type: content_entity_builder.base_field_config.[%parent.id]
          weight:
            type: integer
          applied:
            type: boolean
            label: 'Is Applied'
          index:
            type: boolean
            label: 'Index'            
content_entity_builder.base_field_config.*:
  type: mapping
  label: 'Field settings'
