business_rules.variable.*:
  type: config_entity
  label: 'Variable config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    type:
      type: string
      label: 'Type'
    description:
      type: text
      label: 'Description'
    target_entity_type:
      type: string
      label: 'Entity type'
    target_bundle:
      type: string
      label: 'Bundle'
    tags:
      type: sequence
      label: 'Tags'
      sequence:
        type: string
        label: 'Tag'
    settings:
      type: business_rules.variable.type.[%parent.type]

business_rules.variable.type.entity_filed_variable:
  type: mapping
  label: 'Get value from entity'
  mapping:
    data:
      type: string
      label: 'Data to receive the value'
    field:
      type: string
      label: 'Field'

business_rules.variable.type.entity_empty_variable:
  type: mapping
  label: 'Get value from entity'

business_rules.variable.type.custom_value_variable:
  type: mapping
  label: 'Custom value variable'
  mapping:
    value:
      type: string
      label: 'Value'

business_rules.variable.type.user_variable:
  type: mapping
  label: 'User variable'
  mapping:
    current_or_defined: #current|defined
      type: string
      label: 'Current user or load user by id'
    user_id:
      type: string
      label: 'User id'

business_rules.variable.type.view_result_variable:
  type: mapping
  label: 'View result variable'
  mapping:
    view:
      type: string
      label: 'View'
    arguments:
      type: string
      label: 'Arguments'

#business_rules.variable.type.array_variable:
#  type: mapping
#  label: 'Array variable'
#  mapping:
#    fields:
#      type: sequence
#      label: 'Fields'
#      sequence:
#        type: mapping
#        mapping:
#          id:
#            type: string
#            label: 'Id'
#          label:
#            type: text
#            label: 'Label'
#          type:
#            type: string
#            label: 'Type'
