field.formatter.settings.imagezoom_gallery:
  type: mapping
  label: 'Image Zoom Gallery display settings'
  mapping:
    imagezoom_zoom_type:
      type: string
      label: 'Zoom type'
    imagezoom_display_style:
      type: string
      label: 'Zoom display style'
    imagezoom_zoom_style:
      type: string
      label: 'Zoom style'
    imagezoom_disable:
      type: boolean
      label: 'Zoom disable'
    imagezoom_disable_width:
      type: integer
      label: 'Zoom minimum width'
    imagezoom_additional:
      type: string
      label: 'Additional settings'
