# The body field.storage is part of core, but template included here
# to allow the field.yml action to be used for the body field.
langcode: en
status: true
dependencies:
  module:
    - node
    - text
id: node.@field_name@
field_name: @field_name@
entity_type: node
type: text_with_summary
settings: {  }
module: text
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: true
custom_storage: false
