form_mode_routing.form_routing_entity.*:
  type: config_entity
  label: 'Form routing entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    state:
      type: string
      label: 'State'
    formmode:
      type: string
      label: 'formmode'
    access:
      type: string
      label: 'Who is Allowed'
    path:
      type: string
      label: 'Url'
    title:
      type: string
      label: 'Edit Form Title'
