# Schema for the configuration files of the GTM dataLayer module.

gtm_datalayer.settings:
  type: config_object
  label: 'GTM dataLayer module settings'
  mapping:
    container_id:
      type: string
      label: 'Google Tag Manager container ID'
    debug:
      type: boolean
      label: 'Displayed onscreen debug messages to all users'
    status:
      type: boolean
      label: 'Status'

gtm_datalayer.gtm_datalayer.*:
  type: config_entity
  label: 'dataLayer settings'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: string
      label: 'Label'
    plugin:
      type: string
      label: 'Plugin'
    weight:
      type: integer
      label: 'Weight'
    access_logic:
      type: string
      label: 'Access logic'
    access_conditions:
      type: sequence
      label: 'Access Conditions'
      sequence:
        - type: condition.plugin.[id]
          label: 'Access Condition'
