commerce_payment.commerce_payment_gateway.plugin.payway_frame:
  type: commerce_payment_gateway_configuration
  mapping:
    secret_key_test:
      type: string
      label: 'Secret key (Test)'
    publishable_key_test:
      type: string
      label: 'Publishable key (Test)'
    secret_key:
      type: string
      label: 'Secret key (Live)'
    publishable_key:
      type: string
      label: 'Publishable key (Live)'
