samlauth.authentication:
  type: config_object
  mapping:
    login_menu_item_title:
      type: string
    logout_menu_item_title:
      type: string
    drupal_saml_login:
      type: boolean
    login_redirect_url:
      type: string
    logout_redirect_url:
      type: string
    sp_entity_id:
      type: string
    sp_name_id_format:
      type: string
    sp_cert_folder:
      type: string
    sp_x509_certificate:
      type: string
    sp_private_key:
      type: string
    idp_enity_id:
      type: string
    idp_single_sign_on_service:
      type: string
    idp_single_log_out_service:
      type: string
    idp_change_password_service:
      type: string
    idp_cert_type:
      type: string
    idp_x509_certificate:
      type: string
    idp_x509_certificate_multi:
      type: string
    unique_id_attribute:
      type: string
    map_users:
      type: boolean
    create_users:
      type: boolean
    sync_name:
      type: boolean
    sync_mail:
      type: boolean
    user_name_attribute:
      type: string
    user_mail_attribute:
      type: string
    strict:
      type: boolean
    security_authn_requests_sign:
      type: boolean
    security_logout_requests_sign:
      type: boolean
    security_signature_algorithm:
      type: string
    security_messages_sign:
      type: boolean
    security_request_authn_context:
      type: boolean
    security_lowercase_url_encoding:
      type: boolean
