---
version: '2'

services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/var/www/html/modules/custom/convert_media_tags_to_markup"
      - "./docker-resources:/docker-resources"
    ports:
      - "80"
    links:
      - mysql:mysql
    working_dir: /var/www/html/modules/custom/convert_media_tags_to_markup

  # Database server
  mysql:
    image: mysql:5
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
