custom_pub.custom_publishing_option.*:
  type: config_entity
  label: 'Custom publishing option config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    uuid:
      type: string

custom_pub.configuration.set_custom_publishing_option_value:
  type: mapping
  label: 'Set a custom publish option value on content'
  mapping:
    option:
      type: string
      label: 'Custom Publish Option'
    value:
      type: boolean
      label: 'Value'