custom_configuration.custom_configuration_add:
  path: /admin/config/system/custom_config
  defaults:
    _form: 'Drupal\custom_configuration\Form\ConfigurationSetting'
    _title: 'Add Custom Configuration'
  requirements:
    _permission: 'administer site configuration'
custom_configuration.configuration_list:
  path: /admin/config/system/custom_config/configuration_list
  defaults:
    _form: 'Drupal\custom_configuration\Form\CustomConfigurationList'
    _title: 'Custom Configuration List'
  requirements:
    _permission: 'administer site configuration'
custom_configuration.edit_configuration_list:
  path: /admin/config/system/editConfig/{custom_config_id}
  defaults:
    _form: 'Drupal\custom_configuration\Form\EditConfiguration'
    _title: 'Edit Custom Configuration'
  requirements:
    _permission: 'administer site configuration'
custom_configuration.delete_configuration_list:
  path: /admin/config/system/deleteConfig/{custom_config_id}
  defaults:
    _form: 'Drupal\custom_configuration\Form\DeleteConfiguration'
    _title: 'Delete Custom Configuration'
  requirements:
    _permission: 'administer site configuration'
    
custom_configuration.machine_name:
  path: '/custom_configuration_machine/{key_name}'
  defaults:
    _controller: '\Drupal\custom_configuration\Controller\CustomConfigController::isMachineNameExists'
  requirements:
    _permission: 'access content'
