field.value.aggrid:
  type: mapping
  label: 'Default value'
  mapping:
    value:
      type: string
      label: 'Value'

field.storage_settings.aggrid_id:
  type: mapping
  mapping:
    size:
      type: string
      label: 'ag-Grid Config Entity'

aggrid.general:
  type: config_entity
  label: 'ag-Grid General Settings'
  mapping:
    version:
      type: string
    source:
      type: string
    license_key:
      type: string

aggrid.aggrid.*:
  type: config_entity
  label: 'ag-Grid Entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    aggridDefault:
      type: string
      label: 'ag-Grid Default JSON'
      description: 'Contains header and the default rowData for a new record.'
    addOptions:
      type: string
      label: 'Additional Options'
      description: 'Will always be used for view/edit'
