# @file
# .travis.yml - Drupal 8 Travis CI Integration

language: php

sudo: false

php:
#  - 5.5
  - 5.6
  - 7

# Not sure what this does
#matrix:
#  fast_finish: true

# Set up environment variables.
env:
  global:
    # add composer's global bin directory to the path
    # see: https://github.com/drush-ops/drush#install---composer
    - PATH="$PATH:$HOME/.composer/vendor/bin"

    # Configuration variables.
    - DRUPAL_TI_MODULE_NAME="language_selection_page"

    # Not sure what simpletest group we are using yet.
    - DRUPAL_TI_SIMPLETEST_GROUP="language_selection_page"

    # The environment to use, supported are: drupal-7, drupal-8
    - DRUPAL_TI_ENVIRONMENT="drupal-8"
    - DRUPAL_TI_INSTALL_PROFILE="standard"

    # Drupal specific variables.
    - DRUPAL_TI_DB="drupal_travis_db"
    - DRUPAL_TI_DB_URL="mysql://root:@127.0.0.1/drupal_travis_db"
    # Note: Do not add a trailing slash here.
    - DRUPAL_TI_WEBSERVER_URL="http://127.0.0.1"
    - DRUPAL_TI_WEBSERVER_PORT="8080"
    - DRUPAL_TI_CORE_BRANCH="8.2.x"

    # Simpletest specific commandline arguments, the DRUPAL_TI_SIMPLETEST_GROUP is appended at the end.
    - DRUPAL_TI_SIMPLETEST_ARGS="--verbose --color --concurrency 4 --url $DRUPAL_TI_WEBSERVER_URL:$DRUPAL_TI_WEBSERVER_PORT --module user"

    - DRUPAL_TI_PHPUNIT_ARGS="--testsuite functional --group language_selection_page"
    - DRUPAL_TI_PHPUNIT_CORE_SRC_DIRECTORY="./tests/src"
    
    # This should be automatically set.
    # - SIMPLETEST_BASE_URL="http://127.0.0.1:8080/"
    # - SIMPLETEST_DB="mysql://root:@127.0.0.1/drupal_travis_db"
    # - BROWSERTEST_OUTPUT_DIRECTORY="$TRAVIS_BUILD_DIR"
  matrix:
    #- DRUPAL_TI_RUNNERS="phpunit simpletest behat"
    - DRUPAL_TI_RUNNERS="phpunit-core"


mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8

before_install:
  # Speed up builds by disabling xdebug
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer global require drupal/coder
  - phpcs --config-set installed_paths ~/.composer/vendor/drupal/coder/coder_sniffer
  - phpcs --report=full --standard=Drupal $TRAVIS_BUILD_DIR
  - composer global require "LionsAd/drupal_ti:dev-master"
  - phpenv rehash
  - drupal-ti before_install

install:
  - drupal-ti install

before_script:
  - drupal-ti before_script

script:
  - drupal-ti script

after_script:
  - drupal-ti after_script
