name: 'Configuration Synchronizer'
type: module
description: 'Synchronize your site with updated configuration provided by modules and themes.'
# core: 8.x
php: 5.6
package: Config
configure: config_distro.import
dependencies:
  - config_distro:config_distro
  - config_filter:config_filter
  - config_merge:config_merge
  - config_normalizer:config_normalizer
  - 'config_provider:config_provider (>=8.x-2.x)'
  - config_snapshot:config_snapshot
  - config_update:config_update
  - 'drupal:system (>=8.3)'

# Information added by Drupal.org packaging script on 2018-11-02
version: '8.x-2.0-beta4'
core: '8.x'
project: 'config_sync'
datestamp: 1541177888
