name: 'Configuration Synchronizer'
type: module
description: 'Synchronize your site with updated configuration provided by modules and themes.'
core: 8.x
php: 5.6
package: Config
configure: config_distro.import
dependencies:
  - config_distro:config_distro
  - config_filter:config_filter
  - config_merge:config_merge
  - config_normalizer:config_normalizer
  - 'config_provider:config_provider (>=8.x-2.x)'
  - config_snapshot:config_snapshot
  - config_update:config_update
  - 'drupal:system (>=8.3)'
