media_entity_soundcloud.settings:
  type: config_object
  label: 'Media entity Soundcloud settings'
  mapping:
    thumbnail_destination:
      type: string
      label: 'Destination for thumbnails'

media.source.soundcloud:
  type: media.source.field_aware
  label: '"Soundcloud" media source configuration'

field.formatter.settings.soundcloud_embed:
  type: mapping
  label: 'Field display format settings'
  mapping:
    type:
      type: string
      label: 'Type'
    width:
      type: string
      label: 'Width'
    height:
      type: string
      label: 'Height'
    options:
      type: mapping
      label: 'Options'
      mapping:
        auto_play:
          type: string
          label: 'Autoplay'
        hide_related:
          type: string
          label: 'Hide related'
        show_comments:
          type: string
          label: 'Show comments'
        show_user:
          type: string
          label: 'Show user'
        show_reposts:
          type: string
          label: 'Show reposts'
