visualn_dataset.visualn_data_source.*:
  type: config_entity
  label: 'VisualN Data Source config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    resource_provider_id:
      type: string
      label: 'Resource Provider ID'
    resource_provider_config:
      type: serial
      label: 'Resource Provider config'
