pdb_vue.settings:
  type: config_object
  label: 'PDB Vue settings'
  mapping:
    development_mode:
      type: boolean
      label: 'Toggle the development mode on and off'
    use_spa:
      type: boolean
      label: 'Toggle on to turn the entire page into a Vue instance'
    spa_element:
      type: string
      label: 'The css element that will be used to create a global Vue instance'

block.settings.vue_component:*:
  type: ignore
