mask.translation_symbol:
  type: mapping
  mapping:
    pattern:
      type: string
      label: 'Pattern'
    fallback:
      type: string
      label: 'Fallback'
    optional:
      type: boolean
      label: 'Optional'
    recursive:
      type: boolean
      label: 'Recursive'
    locked:
      type: boolean
      label: 'Locked'

mask.settings:
  type: config_object
  label: 'Mask Field settings'
  mapping:
    use_cdn:
      type: boolean
      label: 'Use a CDN'
    plugin_path:
      type: string
      label: 'Plugin file path'
    translation:
      type: sequence
      label: 'Translation'
      sequence:
        type: mask.translation_symbol
        label: 'Symbol'
