social_auth_pbs.settings:
  type: config_object
  label: 'Social Auth PBS settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    scopes:
      type: string
      label: 'Scopes to be requested'
