block.block.*.third_party.block_aria_landmark_roles:
  type: mapping
  label: Block ARIA Landmark Roles third party settings
  mapping:
    role:
      type: string
      label: A landmark role for the block
    label:
      type: string
      label: A label for the block
