nexx_integration.settings:
  type: config_object
  label: 'nexx Settings'
  mapping:
    video_bundle:
      type: string
      label: 'The bundle of the entity which is used.'
    nexx_api_url:
      type: string
      label:  'The URL to the nexx CRUD API.'
    nexx_api_authkey:
      type: string
      label:  'Authkey for nexx API.'
    omnia_id:
      type: integer
      label:  'The unique identifier of the site, given by nexx.tv.'
    notification_access_key:
      type: string
      label:  'NEXX notification access key.'

media.source.nexx_video:
  type: media.source.field_aware
  label: 'Nexx video configuration'
  mapping:
    channel_field:
      type: string
      label: 'Channel'
    actor_field:
      type: string
      label: 'Actors'
    teaser_image_field:
      type: string
      label: 'Teaser image'

field.value.nexx_video_data:
  type: mapping
  label: 'Default value'
  mapping:
    item_id:
      type: integer 
      label: 'Nexx item ID' 
    title: 
      type: string 
      label: 'Title' 
    hash: 
      type: string 
      label: 'Video hash' 
    thumb: 
      type: string 
      label: 'Thumbnail URL' 
    subtitle: 
      type: string 
      label: 'Subtitle' 
    alttitle: 
      type: string 
      label: 'Alternative title' 
    teaser: 
      type: string 
      label: 'Teaser' 
    uploaded: 
      type: timestamp 
      label: 'Time of upload' 
    channel_id: 
      type: integer 
      label: 'Channel ID' 
    actors_ids: 
      type: string 
      label: 'Actor IDs' 
    tags_ids: 
      type: string 
      label: 'Tag IDs' 
    isSSC: 
      type: boolean 
      label: 'isSSC' 
    encodedSSC: 
      type: boolean 
      label: 'encoded SSC' 
    validfrom_ssc: 
      type: integer
      label: 'Valid from SSC' 
    validto_ssc: 
      type: integer
      label: 'Valid to SSC' 
    encodedHTML5: 
      type: boolean 
      label: 'encoded HTML5' 
    isMOBILE: 
      type: boolean 
      label: 'Is mobile' 
    encodedMOBILE: 
      type: boolean 
      label: 'Encoded mobile' 
    validfrom_mobile: 
      type: integer
      label: 'Valid from mobile' 
    validto_mobile: 
      type: integer
      label: 'Valid to mobile' 
    isHYVE: 
      type: boolean 
      label: 'is HYVE' 
    encodedHYVE: 
      type: boolean 
      label: 'Encoded HYVE' 
    validfrom_hyve: 
      type: integer
      label: 'Valid from HYVE' 
    validto_hyve: 
      type: integer
      label: 'Valid to HYVE' 
    active: 
      type: boolean 
      label: 'Is active' 
    isDeleted: 
      type: boolean 
      label: 'Is deleted' 
    isBlocked: 
      type: boolean 
      label: 'Is blocked' 
    encodedTHUMBS: 
      type: boolean 
      label: 'Encoded thumbs' 
    copyright: 
      type: string 
      label: 'Copyright' 
    runtime: 
      type: string 
      label: 'Runtime'

field.formatter.settings.nexx_video_player:
  type: mapping
  label: 'Nexx Video Player formatter settings'
  mapping:
    autoPlay:
      type: string
      label: 'autoPlay'
    exitMode:
      type: string
      label: 'exitMode'
    disableAds:
      type: string
      label: 'disableAds'
    streamType:
      type: string
      label: 'streamType'
