googleanalyticsmaster.settings:
  type: config_object
  label: 'Google Analytics Master Settings'
  mapping:
    googleanalyticsmaster:
      type: mapping
      mapping:
        tracking_id:
          type: textfield
          label: 'Insert trackind id number'
        tracking_id_admin:
          type: select
          label: '0'
