# Schema for the configuration files of the Imagecache External module.

imagecache_external.settings:
  type: config_object
  label: 'Imagecache External settings'
  mapping:
    imagecache_directory:
      type: string
      label: 'Imagecache directory'
    imagecache_default_extension:
      type: string
      label: 'Imagecache default file extension'
    imagecache_external_batch_flush_limit:
      type: integer
      label: 'Imagecache batch file limit'
    imagecache_external_hosts:
      type: string
      label: 'Imagecache allowed hosts'
    imagecache_external_management:
      type: string
      label: 'Imagecache file management'
    imagecache_external_use_whitelist:
      type: integer
      label: 'Imagecache use whitelist'
    imagecache_fallback_image:
      type: sequence
      label: 'Imagecache fallback image'
      sequence:
        type: string
        label: 'Imagecache fallback image id'
    imagecache_external_allowed_mimetypes:
      type: sequence
      label: 'Imagecache allowed mimetypes'
      sequence:
        type: string
        label: 'Mimetype'
