copyright_block.settings:
  type: config_object
  label: 'Copyright block settings'
  mapping:
    start_year:
      type: string
      label: 'Start year'
    seperator:
      type: string
      label: 'Separator'
    text:
      type: mapping
      mapping:
        value:
          type: text
          label: 'Text value'
        format:
          type: text
          label: 'Format'
