builder_notes.notes:
  type: mapping
  label: 'Builder notes'
  mapping:
    notes:
      type: string
      label: 'Builder notes'

core.entity_view_display.*.*.*.third_party.builder_notes:
  type: builder_notes.notes

core.entity_form_display.*.*.*.third_party.builder_notes:
  type: builder_notes.notes

field.storage.*.*.third_party.builder_notes:
  type: builder_notes.notes

field.field.*.*.*.third_party.builder_notes:
  type: builder_notes.notes

node.type.*.third_party.builder_notes:
  type: builder_notes.notes
