# This file basically is a copy of d7_field_instance_widget_settings.yml with
# unnecessary parts removed and third_party_settings getting filled with Insert
# settings.
id: d7_field_instance_widget_insert_settings
label: Field instance widget Insert configuration
migration_tags:
  - Drupal 7
  - Configuration
source:
  plugin: d7_field_instance_per_form_display
  constants:
    form_mode: default
  source_module: insert
process:
  field_type_exists:
    -
      plugin: migration_lookup
      migration: d7_field
      source:
        - field_name
        - entity_type
    -
      plugin: extract
      index:
        - 0
    -
      plugin: skip_on_empty
      method: row
  bundle:
    plugin: static_map
    source: bundle
    bypass: true
    map:
      comment_node_forum: comment_forum
  form_mode: 'constants/form_mode'
  field_name: field_name
  entity_type: entity_type
  'options/third_party_settings':
    plugin: field_instance_widget_insert_settings
    source: 'widget/settings'
destination:
  plugin: component_entity_form_display_insert
migration_dependencies:
  required:
    - d7_field_instance