assembly.assembly_type.*:
  type: config_entity
  label: 'Assembly type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: string
      label: 'Description'
    visual_styles:
      type: string
      label: 'Visual Styles'
    new_revision:
      type: boolean
      label: 'Whether a new revision should be created by default'
    uuid:
      type: string
