commerce_shipping.commerce_shipping_method.plugin.canadapost:
  type: commerce_shipping_method_configuration
  label: 'Canada Post API settings'
  mapping:
    api:
      type: mapping
      label: 'Information required for connecting to the API'
      mapping:
        customer_number:
          type: string
          label: 'Customer number'
        username:
          type: string
          label: 'Username'
        password:
          type: string
          label: 'Password'
        contract_id:
          type: string
          label: 'Contract ID'
        mode:
          type: string
          label: 'API Mode'
        log:
          type: mapping
          mapping:
            request:
              type: string
              label: 'Log API Requests'
            response:
              type: string
              label: 'Log API Responses'
