filehash.settings:
  type: config_object
  label: 'File hash settings'
  mapping:
    algos:
      type: mapping
      label: 'Enabled hash algorithms'
      mapping:
        md5:
          type: string
          label: 'MD5'
        sha1:
          type: string
          label: 'SHA-1'
        sha256:
          type: string
          label: 'SHA-256'
    dedupe:
      type: boolean
      label: 'Disallow duplicate files'

field.formatter.settings.filehash_table:
  type: mapping
  label: 'File hash table field display format settings'
  mapping:
    algo:
      type: string
      label: 'Hash algorithm'
    use_description_as_link_text:
      type: boolean
      label: 'Replace the file name by its description when available'
