registration_validation.settings:
  type: config_object
  label: 'Registration validation settings'
  mapping:
    domains:
      type: text
      label: 'Blacklisted email domains'
    domains_message:
      type: text
      label: 'Failed validation error message'
    usernames:
      type: text
      label: 'Blacklisted username strings'
    usernames_message:
      type: text
      label: 'Failed validation error message'
    validation_counter:
      type: integer
      label: 'Validation blocked counter'
