hidden_tab_mail_base_url: ''

hidden_tab.hidden_tab_page.*:
  type: config_entity
  label: Hidden Tab Page
  mapping:
    uuid:
      type: string
      label: UUID
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    status:
      type: boolean
      label: Status
    description:
      type: string
      label: description
    created:
      type: int
      label: Created
    changed:
      type: int
      label: Updated
    tab_uri:
      type: string
      label: Tab Uri
      description: The uri from which the page is accessible as a tab.
    secret_uri:
      type: string
      label: Secret Tab Uri
      description: The uri from which the page is accessible as a secret page.
    is_access_denied:
      type: boolean
      label: Is Access Denied
      description: Whether an access deniend exception should be raised in case of illegal access, or simply not found.
    target_entity_type:
      type: string
      label: Target Entity Type
      description: Target entity type the page is attached and limited to.
    target_entity_bundle:
      type: string
      label: Target Entity Bundle
      description: Target bundle of the target entity type the page is attached and limited to.
    tab_view_permission:
      type: string
      label: Tab View Permissions
      description: The permission required to view the tab.
    secret_uri_view_permission:
      type: string
      description: The permission required to view the secret page from the secret Uri.
    credit_check_order:
      type: string
      label: Credit Check Order
      description: Credit checking order, mechanism of Credit Service. Check it for more information.
    template:
      type: string
      label: Template
      description: Template used to render the page.
    inline_template:
      type: string
      label: Inline Template
      description: Inline template stored and used to render the page, overrides the template option.
    inline_template_region_count:
      type: string
      label: Inline Template Region Count
      description: How many regions should be populated for the inline template if it is set.

hidden_tab.hidden_tab_placement.*:
  type: config_entity
  label: Hidden Tab Placement
  mapping:
    uuid:
      type: string
      label: UUID
    id:
      type: string
      label: ID
    description:
      type: string
      label: description
    created:
      type: int
      label: Created
    changed:
      type: int
      label: Updated
    status:
      type: boolean
      label: Status
    target_hidden_tab_page:
      type: string
      label: Target Hidden Tab Page
      description: The target Hidden Tab Page the entity is attached to.
    target_user:
      type: string
      label: Target User
      description: The target user the the entity is attached to. NOT IMPLEMENTED.
    target_entity:
      type: string
      label: Target Entity
      description: The target entity the the entity is attached to. NOT IMPLEMENTED.
    target_entity_type:
      type: string
      label: Target Entity Type
      description: The target entity type the entity is attached to. NOT IMPLEMENTED.
    target_entity_bundle:
      type: string
      label: Target Entity Bundle
      description: The bundle of the target entity type the entity is attached to. NOT IMPLEMENTED.
    weight:
      type: integer
      label: Weight
      description: Weight of the entity among other entities, used for order of rendering.
    region:
      type: string
      label: Region
      description: The region in the template the entity is put into.
    view_permissions:
      type: string
      label: View Permissions
      description: The permission required to view the entity.
    komponent_type:
      type: string
      label: Komponent Type
      description: The type, such as views.
    komponent:
      type: string
      label: komponent
      description: The actual komponent, such as a specific display of a view.
    komponent_configuration:
      type: string
      label: Komponent Configuration
      description: Arbitrary serialized (json_encoded) configuration of the komponent.
