appbanners.settings:
  type: config_object
  label: 'App Banners settings'
  mapping:
    ios_app_id:
      type: string
      label: 'The iOS App ID'
    ios_affiliate_data:
      type: string
      label: 'iOS Affiliate Data'
    ios_app_argument:
      type: string
      label: 'iOS App Argument'

    android_app_id:
      type: string
      label: 'Android App ID'
    android_short_name:
      type: string
      label: 'Android Short Name'
    android_name:
      type: string
      label: 'Android Name'
    android_icon:
      type: string
      label: 'Android Icon (192px)'
    android_icon_large:
      type: string
      label: 'Android Icon (512px)'

    admin:
      type: boolean
      label: 'Include app banners tags on admin pages?'
    visibility:
      type: string
      label: 'Whether to include or exclude pages listed in "pages" field'
    pages:
      type: text
      label: 'Include script on specific pages'
