field.widget.settings.external_data_source_autocomplete_widget:
  type: mapping
  label: 'External Data Source Auto complete  widget settings'
  mapping:
    size:
      type: integer
      label: 'Size of Select field'
    placeholder:
      type: string
      label: 'Placeholder'
field.widget.settings.external_data_source_select_widget:
  type: mapping
  label: 'External Data Source Select widget settings'
  mapping:
    size:
      type: integer
      label: 'Size of Select field'
    placeholder:
      type: string
      label: 'Placeholder'
field.widget.settings.external_data_source_checkboxes_widget:
  type: mapping
  label: 'External Data Source Checkboxes widget settings'
  mapping:
    size:
      type: integer
      label: 'Size of Select field'
    placeholder:
      type: string
      label: 'Placeholder'