bibcite_entity.reference.settings:
  type: config_object
  label: 'Common reference settings'
  mapping:
    ui_override:
      type: mapping
      mapping:
        enable_form_override:
          type: boolean
          label: 'Enable UI override'
    display_override:
      type: mapping
      mapping:
        reference_page_view_mode:
          type: string
          label: 'Reference view mode'
    links:
      type: sequence
      sequence:
        type: bibcite_entity.link
