warmer.settings.warmer_plugin.cdn:
  type: mapping
  mapping:
    id:
      type: string
    frequency:
      type: integer
    batchSize:
      type: integer
    urls:
      type: sequence
      sequence:
        type: string
    headers:
      type: sequence
      sequence:
        type: string

warmer.settings.warmer_plugin.sitemap:
  type: mapping
  mapping:
    id:
      type: string
    frequency:
      type: integer
    batchSize:
      type: integer
    minPriority:
      type: float
    sitemaps:
      type: sequence
      sequence:
        type: string
    headers:
      type: sequence
      sequence:
        type: string
