miniorange_oauth_client.settings:
  type: mapping
  label: Settings
  mapping:
    miniorange_oauth_client_customer_admin_email:
      type: 'NULL'
    miniorange_oauth_client_license_key:
      type: 'NULL'
    miniorange_oauth_client_customer_id:
      type: string
    miniorange_oauth_client_customer_admin_token:
      type: string
    miniorange_oauth_client_customer_api_key:
      type: string
    miniorange_oauth_client_force_auth:
      type: boolean
    miniorange_oauth_client_enable_backdoor:
      type: boolean
    miniorange_oauth_client_default_relaystate:
      type: string
    miniorange_oauth_client_name:
      type: string
    miniorange_oauth_client_issuer:
      type: string
    miniorange_oauth_client_login_url:
      type: string
    miniorange_oauth_client_logout_url:
      type: string
    miniorange_oauth_client_x509_certificate:
      type: string
    miniorange_oauth_client_response_signed:
      type: boolean
    miniorange_oauth_client_assertion_signed:
      type: boolean
    miniorange_oauth_client_enable_login:
      type: boolean
    miniorange_oauth_client_username_attribute:
      type: string
    miniorange_oauth_client_email_attribute:
      type: string
    miniorange_oauth_client_attr1_name:
      type: string
    miniorange_oauth_client_attr5_name:
      type: string
    miniorange_oauth_client_attr5_name:
      type: string
    miniorange_oauth_client_attr2_name:
      type: string
    miniorange_oauth_client_attr2_name:
      type: string
    miniorange_oauth_client_attr3_name:
      type: string
    miniorange_oauth_client_attr3_name:
      type: string
    miniorange_oauth_client_attr4_name:
      type: string
    miniorange_oauth_client_attr4_name:
      type: string
    miniorange_oauth_client_disable_autocreate_users:
      type: boolean
    miniorange_oauth_client_default_role:
      type: string
    miniorange_oauth_client_role1_name:
      type: string
    miniorange_oauth_client_role1_name:
      type: string
    miniorange_oauth_client_role2_name:
      type: string
    miniorange_oauth_client_role2_name:
      type: string
    miniorange_oauth_client_role3_name:
      type: string
    miniorange_oauth_client_role3_name:
      type: string
    miniorange_oauth_client_role4_name:
      type: string
    miniorange_oauth_client_role4_name:
      type: string
    miniorange_oauth_client_status:
      type: string
    miniorange_oauth_client_customer_admin_phone:
      type: 'NULL'
    miniorange_oauth_client_tx_id:
      type: 'NULL'
    miniorange_oauth_client_customer_admin_password:
      type: string
    miniorange_oauth_client_auto_redirect_to_idp:
      type: boolean
    miniorange_oauth_client_sp_issuer:
      type: string
    miniorange_oauth_client_login_by:
      type: integer
    miniorange_oauth_client_attr1_name:
      type: string
    miniorange_oauth_client_entity_id:
      type: string
    miniorange_oauth_client_base_url : 
      type: string  
    miniorange_oauth_client_acs_url:
      type: string  
    miniorange_oauth_client_nameid_attr_map:
      type: string