feadmin.settings:
  type: config_object
  label: 'Front-End Administration module settings'
  mapping:
    tools:
      type: sequence
      label: 'Tools defined'
      sequence:
        type: feadmin_tool
        label: 'FeAdmin tool ID'

feadmin_tool:
  type: config_object
  mapping:
    enabled:
      type: boolean
      label: Enabled
    weight:
      type: integer
      label: Weight
