stages:
  - lint
  - tests

before_script:
  - apk add --update --upgrade git libpng-dev
  - docker-php-ext-configure gd
  - docker-php-ext-install gd
  - curl -sSL https://getcomposer.org/composer.phar -o /usr/local/bin/composer && chmod a+x /usr/local/bin/composer
  - composer global require hirak/prestissimo
  - composer install

# Lint
.lint:
  stage: lint
  image: php:7.2-alpine
  tags: [docker]

phpcs:
  extends: .lint
  script:
    - composer phpcs

phpmd:
  extends: .lint
  script:
    - composer phpmd

phpstan:
  extends: .lint
  script:
    # phpstan support PHP >= 7.1 so in order to test with versions below
    # it cannot be a require dev in the committed composer.json.
    - composer require --dev phpstan/phpstan
    - composer phpstan

# Test
.test:
  stage: tests
  image: php:${PHP_VERSION}-alpine
  tags: [docker]
  script:
    - composer phpunit

php-5.6:
  extends: .test
  variables:
    PHP_VERSION: "5.6"

php-7.0:
  extends: .test
  variables:
    PHP_VERSION: "7.0"

php-7.1:
  extends: .test
  variables:
    PHP_VERSION: "7.1"

php-7.2:
  extends: .test
  variables:
    PHP_VERSION: "7.2"
