services:
  nimbus.file_detection.module:
    class: Drupal\nimbus_module_config\EventSubscriber\FileDetection\ModuleDirectoriesSubscriber
    arguments: ['@module_handler']
    tags:
      - { name: event_subscriber }
