affiliates_connect_amazon.settings:
  type: config_object
  label: 'Affiliates Connect Amazon settings'
  mapping:
    locale:
      type: string
      label: 'Location'
    native_api:
      type: boolean
      label: 'Allows usage Affiliate Marketing using tracking ID'
    amazon_associate_id:
      type: string
      label: 'Input associated ID of corresponding Affiliate API'
    amazon_access_key:
      type: string
      label: 'Input access key of corresponding Affiliate API'
    amazon_secret_key:
      type: string
      label: 'Input associated token of corresponding Affiliate API'
    data_storage:
      type: boolean
      label: 'Allows storing product data in your site database'
    full_content:
      type: boolean
      label: 'Allows updating of full content'
    price:
      type: boolean
      label: 'Allows updating of price'
    available:
      type: boolean
      label: 'Allows updating of products availability'
    size:
      type: boolean
      label: 'Allows updating of size'
    color:
      type: boolean
      label: 'Allows updating of color'
    offers:
      type: boolean
      label: 'Allows updating of offers'
