# Schema for the configuration files of the Past module.

past.settings:
  type: config_object
  label: 'Past settings'
  mapping:
    events_expire:
      type: integer
      label: 'Log expiration interval'
    shutdown_handling:
      type: boolean
      label: 'Register PHP shutdown error handler'
    exception_handling:
      type: boolean
      label: 'Register PHP exception handler'
    log_session_id:
      type: boolean
      label: 'Log the session id'
    log_watchdog:
      type: boolean
      label: 'Log watchdog to past event log'
    log_cache_tags:
      type: boolean
      label: 'Log cache tag invalidations'
    max_recursion:
      type: integer
      label: 'Maximum level of recursion when printing an event argument'
    backtrace_include:
      type: sequence
      label: 'Include watchdog severity levels from writing backtraces'
      sequence:
        type: integer
    severity_threshold:
      type: integer
      label: 'Threshold'
