# General settings.
monitoring.settings:
  type: config_object
  label: 'Monitoring settings'
  mapping:
    sensor_call_logging:
      type: string
      label: 'Call logging'
    cron_run_sensors:
      type: boolean
      label: 'Run sensors during cron runs'

# Config schema for sensor config entity.
monitoring.sensor_config.*:
  type: config_entity
  label: 'Monitoring Sensor'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Sensor Label'
    description:
      type: text
      label: 'Description'
    category:
      type: string
      label: 'Category'
    plugin_id:
      type: string
      label: 'Sensor plugin ID'
    result_class:
      type: string
      label: 'Result Class'
    value_label:
      type: string
      label: 'Value Label'
    value_type:
      type: string
      label: 'Value Type'
    status:
      type: boolean
      label: 'Enabled'
    caching_time:
      type: integer
      label: 'Sensor Caching Time'
    settings:
      type: monitoring.settings.[%parent.plugin_id]
      label: 'Settings'
    thresholds:
      type: mapping
      label: 'Threshold'
      mapping:
        type:
          type: string
          label: 'Type'
        warning:
          type: integer
          label: 'Warning'
        critical:
          type: integer
          label: 'Critical'
        warning_low:
          type: integer
          label: 'Warning'
        critical_low:
          type: integer
          label: 'Critical'
        warning_high:
          type: integer
          label: 'Warning'
        critical_high:
          type: integer
          label: 'Critical'

# Base type for settings with common settings.
monitoring.settings_base:
  type: mapping
  mapping:
    result_logging:
      type: boolean
      label: Result logging

# Base settings for database and entity aggregators.
monitoring.settings.aggregator_base:
  type: monitoring.settings_base
  mapping:
    time_interval_field:
      type: string
      label: 'Time interval field'
    time_interval_value:
      type: integer
      label: 'Time interval value'
    conditions:
      type: sequence
      label: Conditions
      sequence:
        type: mapping
        mapping:
          field:
            type: string
          value:
            type: string
          operator:
            type: string
    verbose_fields:
      type: sequence
      label: Verbose fields
      sequence:
        type: string
        label: 'Field'

monitoring.settings.database_aggregator:
  type: monitoring.settings.aggregator_base
  mapping:
    table:
      type: string
      label: 'Table'
    history_status:
      type: boolean
      label: 'History status'

monitoring.settings.entity_aggregator:
  type: monitoring.settings.aggregator_base
  label: 'Entity aggregator sensor settings'
  mapping:
    entity_type:
      type: string
      label: 'Table'
    verbose_fields:
      type: sequence
      label: Fields / Attributes
      sequence:
        type: string
        label: The field to display

monitoring.settings.monitoring_git_dirty_tree:
  type: monitoring.settings_base
  label: 'Dirty git tree sensor settings'
  mapping:
    repo_path:
      type: string
      label: 'Repository path'
    status_cmd:
      type: string
      label: 'Status command'
    check_branch:
      type: boolean
      label: 'Should check branch'
    ahead_cmd:
      type: string
      label: 'Ahead command'
    branches_cmd:
      type: string
      label: 'Branches command'
    actual_branch_cmd:
      type: string
      label: 'Actual branch command'
    expected_branch:
      type: string
      label: 'Git branch'
    submodules_cmd:
      type: string
      label: 'Check submodules command'

monitoring.settings.monitoring_disappeared_sensors:
  type: monitoring.settings_base
  label: 'Disappaered sensor settings'

monitoring.settings.queue_size:
  type: monitoring.settings_base
  label: 'Queue size sensor settings'
  mapping:
    queue:
      type: string
      label: Name of the queue

monitoring.settings.update_status:
  type: monitoring.settings_base
  label: 'Update status sensor settings'
  mapping:
    type:
      type: string
      label: Type of updates to check

monitoring.settings.core_requirements:
  type: monitoring.settings_base
  label: 'Core requirements sensor settings'
  mapping:
    module:
      type: string
      label: 'Module name'
    exclude_keys:
      type: sequence
      label: 'Exclude list'
      sequence:
        type: string
        label: 'Exclude key'

monitoring.settings.payment_turnover:
  type: monitoring.settings.entity_aggregator
  label: 'Payment turnover sensor settings'
  mapping:
    currency_code:
      type: string
      lavel: Currency code

monitoring.settings.view_display_aggregator:
  type: monitoring.settings_base
  label: 'View display aggregator sensor settings'
  mapping:
    view:
      type: string
      label: 'View'
    display:
      type: string
      label: 'Display'

monitoring.settings.search_api_unindexed:
  type: monitoring.settings_base
  label: 'Search Api settings'
  mapping:
    index_id:
      type: string
      label: 'Index ID'

monitoring.settings.watchdog_aggregator:
  type: monitoring.settings.database_aggregator
  label: 'Watchdog sensor settings'

monitoring.settings.php_notices:
  type: monitoring.settings.watchdog_aggregator
  label: 'PHP notices sensor settings'

monitoring.settings.dblog_404:
  type: monitoring.settings.database_aggregator
  label: '404 settings'

monitoring.settings.image_style_missing:
  type: monitoring.settings.database_aggregator
  label: 'Missing images sensor settings'

monitoring.settings.temporary_files_usages:
  type: monitoring.settings.database_aggregator
  label: 'Temporary files usages sensor settings'

monitoring.settings.redirect_404:
  type: monitoring.settings.database_aggregator
  label: 'Redirect 404 sensor settings'

monitoring.settings.user_integrity:
  type: monitoring.settings_base
  label: 'Privileged user integrity'

monitoring.settings.user_failed_logins:
  type: monitoring.settings.watchdog_aggregator
  label: 'Failed user sensor settings'

monitoring.settings.user_void_failed_logins:
  type: monitoring.settings.watchdog_aggregator
  label: 'Failed user sensor settings'

monitoring.settings.twig_debug_mode:
  type: monitoring.settings_base
  label: 'Monitor twig settings'

monitoring.settings.disk_usage:
  type: monitoring.settings_base
  label: 'Monitor disk space usage'
  mapping:
    directory:
      label: Directory
      type: string

monitoring.settings.system_load:
  type: monitoring.settings_base
  label: 'Monitor system load'
  mapping:
    average_monitored:
      label: Average
      type: string

monitoring.settings.monitoring_installed_modules:
  type: monitoring.settings_base
  label: 'Installed modules sensor settings'
  mapping:
    allow_additional:
      label: Allow additional
      type: boolean
    modules:
      label: Installed modules
      type: sequence
      sequence:
        type: string
        label: 'Module name'

monitoring.settings.config_value:
  type: monitoring.settings_base
  label: 'Config sensor settings'
  mapping:
    config:
      type: string
      label: 'Type'
    key:
      type: string
      label: 'Key'
    value:
      # Value can be of different type (string, ...), depending on the settings.
      type: ignore
      label: 'Value'

monitoring.settings.state_value:
  type: monitoring.settings_base
  label: 'State sensor settings'
  mapping:
    key:
      type: string
      label: 'Key'
    value:
      # Value can be of different type (string, ...), depending on the settings.
      type: ignore
      label: 'Value'

monitoring.settings.cron_last_run_time:
  type: monitoring.settings_base
  label: 'Cron last run time sensor settings'
  mapping: { }

monitoring.settings.ultimate_cron_errors:
  type: monitoring.settings_base
  label: 'Ultimate cron errors sensor settings'

monitoring.settings.database_disk_usage:
  type: monitoring.settings_base
  label: 'Monitors how much space the database uses'

monitoring.settings.solr_disk_usage:
  type: monitoring.settings_base
  label: 'Solr disk usage'
  mapping:
    server:
      label: 'Server'
      type: string

monitoring.settings.monitoring_system_memory:
  type: monitoring.settings_base
  label: 'System memory sensor settings'
  mapping:
    memory:
      type: string
      label: 'Memory'
    value:
      type: string
      label: 'Value'
