commerce_payment.commerce_payment_gateway.plugin.sips_payment:
  type: commerce_payment_gateway_configuration
  mapping:
    sips_interface_version:
      type: string
      label: 'Interface version'
    sips_key_version:
      type: string
      label: 'Key version'
    sips_merchant_id:
      type: string
      label: 'Merchant id'
    sips_passphrase:
      type: string
      label: 'Passphrase'
    sips_payment_method:
      type: string
      label: 'Payment method (i.e. VISA, ...)'
