# Schema for the configuration files of the improved_multi_select module.

improved_multi_select.settings:
  type: config_object
  label: 'Improved Multi Select settings'
  mapping:
    isall:
      type: boolean
      label: 'Replace all multi-select lists'
    url:
      type: string
      label: 'Replace multi-select lists on specific pages'
    selectors:
      type: string
      label: 'Replace multi-select with specified selectors'
    filtertype:
      type: string
      label: 'Filter functionality'
    orderable:
      type: boolean
      label: 'Allow re-ordering of selected items'
    groupresetfilter:
      type: boolean
      label: 'Reset filter when selecting a group'
    buttontext_add:
      type: string
      label: 'Add button text'
    buttontext_addall:
      type: string
      label: 'Add all button text'
    buttontext_del:
      type: string
      label: 'Remove button text'
    buttontext_delall:
      type: string
      label: 'Delete all button text'
    buttontext_moveup:
      type: string
      label: 'Move up button text'
    buttontext_movedown:
      type: string
      label: 'Move down button text'
