# Schema for the configuration files of the Field Redirection module.
field.formatter.settings.field_redirection_formatter:
  type: mapping
  label: ''
  mapping:
    code:
      type: integer
      label: 'HTTP status code'
    404_if_empty:
      type: boolean
      label: '404 if URL empty'
    page_restrictions:
      type: integer
      label: 'Redirect page restrictions'
    pages:
      type: string
      label: 'Paths'
