get_linkedin_posts.settings:
  type: config_object
  label: 'Get Linkedin Posts settings'
  mapping:
    linkedin_import:
      type: boolean
      label: 'Enable importing Linkedin Posts'
    linkedin_companies:
      type: sequence
      label: 'Companies for import posts'
    linkedin_count:
      type: integer
      label: 'Posts count'
    linkedin_expire:
      type: integer
      label: 'Delete old posts'
    linkedin_client_id:
      type: string
      label: 'Client Id'
    linkedin_client_secret:
      type: string
      label: 'Client secret'
    linkedin_access_token:
      type: string
      label: 'Token'
    linkedin_access_token_expires:
      type: string
      label: 'Expiry'
    linkedin_admin_email:
      type: email
      label: 'Stay informed about token expire'
