cors_ui_list:
  type: sequence
  sequence:
    type: string

cors_ui.configuration:
  type: mapping
  mapping:
    enabled:
      label: 'Enabled'
      type: boolean
    allowedHeaders:
      label: 'Allowed Headers'
      type: cors_ui_list
    allowedMethods:
      label: 'Allowed Methods'
      type: cors_ui_list
    allowedOrigins:
      label: 'Allowed Origins'
      type: cors_ui_list
    exposedHeaders:
      label: 'Exposed Headers'
      type: cors_ui_list
    maxAge:
      label: 'Max Age'
      type: integer
    supportsCredentials:
      label: 'Supports Credentials'
      type: boolean
