shurly.settings:
  type: mapping
  label: Settings
  mapping:
    shurly_base:
     type: string
    shurly_redirect_page:
      type: boolean
    shurly_forbid_localhost:
      type: boolean
    shurly_forbid_private_ips:
      type: boolean
    shurly_forbid_unresolvable_hosts:
      type: boolean
    shurly_forbid_ips:
      type: boolean
    shurly_forbid_custom:
      type: boolean
    shurly_custom_restriction:
      type: string
    shurly_gsb:
      type: 'NULL'
    shurly_gsb_client:
      type: boolean
    shurly_gsb_apikey:
      type: 'NULL'
    shurly_length:
      type: integer
    shurly_counter:
      type: integer
    shurly_index:
      type: string
    shurly_gsb_config_client:
      type: 'NULL'
