# Schema for the configuration files of the CRM Core User Synchronization module.
crm_core_user_sync.settings:
  type: config_object
  label: 'CRM Core User Synchronization settings'
  mapping:
    rules:
      type: sequence
      label: 'Rules'
      sequence:
        type: crm_core_user_sync.rule
    auto_sync_user_create:
      type: boolean
      label: 'Auto sync user create'
    contact_load:
      type: boolean
      label: 'Load contact related to the current user'
    contact_show:
      type: boolean
      label: 'Show related contact information on the user profile'

crm_core_user_sync.rule:
  type: mapping
  label: 'Rule'
  mapping:
    role:
      type: string
      label: 'Role'
    contact_type:
      type: string
      label: 'Contact type'
    enabled:
      type: boolean
      label: 'Enabled'
    weight:
      type: integer
      label: 'Weight'
