webserver_auth.settings:
  type: config_object
  label: 'Webserver Authentication Settings'
  mapping:
    create_user:
      type: boolean
      label: 'Automatically create user when user does not exist in the Drupal user table'
    email_domain:
      type: string
      label: 'Email domain'
    disallow_username_change:
      type: boolean
      label: 'isable option to change username'
    disallow_pw_change:
      type: boolean
      label: 'Remove option to change password'
    block_access_to_the_site:
      type: boolean
      label: 'Block access to the site if webserver username is not provided'
    block_access_redirect_url:
      type: string
      label: 'URL redirect if access is blocked'
    strip_prefix:
      type: boolean
      label: 'Strip prefix'
    strip_domain:
      type: boolean
      label: 'Strip domain'
    login_url:
      type: string
      label: 'Login URL'
    logout_url:
      type: string
      label: 'Logout URL'
    register_url:
      type: string
      label: 'Register URL'