ad_entity.settings.generic:
  type: mapping
  label: 'Global settings for the Generic type.'
  mapping:
    page_targeting:
      type: mapping
      label: 'Page targeting'
      mapping:
        enabled:
          type: boolean
          label: 'Provide page targeting as a global JavaScript variable.'
        js_variable:
          type: string
          label: 'Page targeting JavaScript variable'

ad_entity.ad_entity.*.third_party_settings.ad_entity_generic:
  type: mapping
  label: 'Entity config for generic ads'
  mapping:
    id:
      type: string
      label: 'Identifier'
    format:
      type: string
      label: 'Display format'
    targeting:
      type: ignore
      label: 'Default pairs of key-values for targeting on the ad tag'
