# Schema for the configuration files of the elFinder module.

elfinder.settings:
  type: mapping
  label: 'elFinder settings'
  mapping:
    thumbnail:
      type: mapping
      label: 'Thumbnail'
      mapping:
        size:
          type: integer
          label: 'Image size'
        dirname:
          type: string
          label: 'Directory Name'
        imglib:
          type: string
          label: 'Image Processing Library'
        tmbcrop:
          type: boolean
          label: 'Thumbnail Cropping'
    filesystem:
      type: mapping
      label: 'Filesystem'
      mapping:
        mimedetect:
          type: string
          label: 'MIME Detection Method'
        fileperm:
          type: string
          label: 'Created file permissions'
        dirperm:
          type: string
          label: 'Created directory permissions'
        maxfilesize:
          type: string
          label: 'Maximum File Size'
        maxfilecount:
          type: integer
          label: 'Maximum folder size'
        public_root_label:
          type: string
          label: 'Public Files Tree Label'
        private_root_label:
          type: string
          label: 'Private Files Tree Label'
        unmanaged_root_label:
          type: string
          label: 'Unmanaged Files Tree Label'
        root_custom:
          type: string
          label: 'Custom Root Directory Path'
        url_custom:
          type: string
          label: 'Custom Root Directory Url Prefix'
        handleprivate:
          type: boolean
          label: 'Handle Private File Downloads'
        owner_format:
          type: string
          label: 'File Owner Format String'
        allowed_extensions:
          type: string
          label: 'List of Allowed File Extensions'
        fileurl:
          type: boolean
          label: 'File Url'
    misc:
      type: mapping
      label: 'Miscellateous'
      mapping:
        rememberlastdir:
          type: boolean
          label: 'Remember Last Opened Directory'
        requesttype:
          type: string
          label: 'Filesystem Connector Protocol HTTP Request'
        manager_width:
          type: integer
          label: 'File Manager Width'
        manager_height:
          type: integer
          label: 'File Manager Height'
        usesystemjquery:
          type: boolean
          label: 'Use Drupal Built-In jQuery'

elfinder.profile.*:
  type: config_entity
  label: 'elFinder Profile'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Name'
    description:
      type: label
      label: 'Description'
    conf:
      type: sequence
      label: 'Configuration'
      sequence:
        - type: elfinder.profile_conf.[%key]
        

elfinder.profile_conf.mimedetect:
  type: string
  label: 'File type detection'

elfinder.profile_conf.file_url_type:
  type: string
  label: 'Selected file url type'

elfinder.profile_conf.fileperm:
  type: string
  label: 'Created file permissions'

elfinder.profile_conf.dirperm:
  type: string
  label: 'Created directory permissions'

elfinder.profile_conf.maxfilesize:
  type: string
  label: 'Maximum upload size'

elfinder.profile_conf.user_quota:
  type: string
  label: 'User quota'

elfinder.profile_conf.tmbsize:
  type: integer
  label: 'Thumbnail size'

elfinder.profile_conf.tmbdirname:
  type: string
  label: 'Thumbnail directory name'

elfinder.profile_conf.imglib:
  type: string
  label: 'Image manipulation library'

elfinder.profile_conf.tmbcrop:
  type: string
  label: 'Image crop'

elfinder.profile_conf.rememberlastdir:
  type: string
  label: 'Remember last opened directory'

elfinder.profile_conf.manager_width:
  type: integer
  label: 'File manager width'

elfinder.profile_conf.manager_height:
  type: integer
  label: 'File manager height'
  
elfinder.profile_conf.ckeditor_upload_directory:
  type: string
  label: 'CKEditor Upload Path'

elfinder.profile_conf.roles:
  type: sequence
  label: 'Assigned roles'
  sequence:
    - type: string
      label: 'User role'
   

elfinder.profile_conf.volumes:
  type: sequence
  label: 'Volumes'
  sequence:
    - type: mapping
      label: 'Volume'
      mapping:
        path:
          type: string
          label: 'Path'
        label:
          type: string
          label: 'Label'
        url:
          type: string
          label: 'Url'
