# Schema for the configuration files of the Tocify module.

tocify.settings:
  type: config_object
  label: 'Tocify settings'
  mapping:
    _theme:
      type: string
      label: 'Theme'
    _context:
      type: string
      label: 'Context'
    selectors:
      type: string
      label: 'Selectors'
    show_and_hide:
      label: 'Show and hide'
      type: boolean
    show_effect:
      type: string
      label: 'Show effect'
    show_effect_speed:
      type: string
      label: 'Show effect speed'
    hide_effect:
      type: string
      label: 'Hide effect'
    hide_effect_speed:
      type: string
      label: 'Hide effect speed'
    smooth_scroll:
      type: boolean
      label: 'Smooth scroll'
    smooth_scroll_speed:
      type: string
      label: 'Smooth scroll speed'
    scroll_to:
      type: integer
      label: 'Scroll to'
    show_and_hide_on_scroll:
      type: boolean
      label: 'Show and hide on scroll'
    highlight_on_scroll:
      type: boolean
      label: 'Highlight on scroll'
    highlight_offset:
      type: integer
      label: 'Highlight offset'
    extend_page:
      type: boolean
      label: 'Extend page'
    extend_page_offset:
      type: integer
      label: 'Extend page offset'
    history:
      type: boolean
      label: 'History'
    hash_generator:
      type: string
      label: 'Hash generator'
    highlight_default:
      type: boolean
      label: 'Highlight default'
    ignore_selector:
      type: string
      label: 'Ignore selector'
    scroll_history:
      type: boolean
      label: 'Scroll history'
