ad_entity.settings.adtech_factory:
  type: mapping
  label: 'Global settings for the AdTech Factory type.'
  mapping:
    library_source:
      type: string
      label: 'Library source'
    page_targeting:
      type: ignore
      label: 'Default pairs of key-values for targeting on the page'

ad_entity.ad_entity.*.third_party_settings.ad_entity_adtech:
  type: mapping
  label: 'Entity config for AdTech Factory ads'
  mapping:
    data_atf:
      type: string
      label: 'Value for the data-atf attribute on the ad tag'
    data_atf_format:
      type: string
      label: 'Value for the data-atf-format attribute on the ad tag'
    targeting:
      type: ignore
      label: 'Default pairs of key-values for targeting on the ad tag'
    iframe:
      type: mapping
      label: 'iFrame view settings'
      mapping:
        width:
          type: string
          label: 'iFrame width'
        height:
          type: string
          label: 'iFrame height'
        title:
          type: string
          label: 'Value for the title attribute'
