tmgmt.translator.settings.smartling:
  type: tmgmt.translator_base
  mapping:
    project_id:
      type: string
      label: 'Project ID'
    user_id:
      type: string
      label: 'User ID'
    token_secret:
      type: string
      label: 'Token Secret'
    auto_authorize_locales:
      type: boolean
      label: 'Automatically authorize content for translation in Smartling'
    callback_url_use:
      type: boolean
      label: 'Use Smartling callback: /smartling/callback/%cron_key'
    callback_url_host:
      type: string
      label: 'Override callback url host'
    retrieval_type:
      type: string
      label: 'The desired format for the download'
    allow_override:
      type: boolean
      label: 'Allow override translation file on smartling side'
    scheme:
      type: string
      label: 'Schema to store translation files in'
    contextUsername:
      type: string
      label: 'Username for context retrieval'
    context_silent_user_switching:
      type: boolean
      label: 'Context silent user authentication'
    context_skip_host_verifying:
      type: boolean
      label: 'Skip host verification'
    custom_regexp_placeholder:
      type: string
      label: 'Custom RegExp Placeholder'
    export_format:
      type: string
      label: 'Export format for file type'
    identical_file_name:
      type: boolean
      label: 'Use identical file names for jobs that contain identical content'
    enable_smartling_logging:
      type: boolean
      label: 'Enable Smartling logging'
    enable_notifications:
      type: boolean
      label: 'Enable Smartling notifications'
    async_mode:
      type: boolean
      label: 'Asynchronous mode'
    enable_basic_auth:
      type: boolean
      label: 'Enable basic auth for context'
    basic_auth:
      type: mapping
      label: 'Basic auth'
      mapping:
        login:
          type: string
          label: 'Login'
        password:
          type: string
          label: 'Password'

action.configuration.tmgmt_smartling_send_context_action:
  type: action_configuration_default
  label: 'Send context action'
