id: d7_payment_pack_check_settings
label: Payment Pack check configuration settings
migration_tags:
  - Drupal 7
  - Configuration

source:
  plugin: variable
  source_module: uc_payment_pack
  variables:
    - uc_check_policy
    - uc_check_address

process:
  policy: uc_check_policy
  'mailing_address/name': 'uc_check_address/uc_check_mailing_name'
  'mailing_address/company': 'uc_check_address/uc_check_mailing_company'
  'mailing_address/street1': 'uc_check_address/uc_check_mailing_street1'
  'mailing_address/street2': 'uc_check_address/uc_check_mailing_street2'
  'mailing_address/city': 'uc_check_address/uc_check_mailing_city'
  'mailing_address/zone': 'uc_check_address/uc_check_mailing_zone'
  'mailing_address/postal_code': 'uc_check_address/uc_check_mailing_postal_code'
  'mailing_address/country': 'uc_check_address/uc_check_mailing_country'

destination:
  plugin: config
  config_name: uc_payment_pack.check.settings
