better_passwords.settings:
  type: config_object
  mapping:
    length:
      type: integer
      label: 'Minimum passphrase length'
    strength:
      type: integer
      label: 'Minimum passphrase strength'
    auto_generate:
      type: integer
      label: 'Auto-generate passwords'
