---
# <MODULE_NAME>.<ENTITY_ID>
sdk.sdk.*:
  type: config_object
  label: SDK
  mapping:
    id:
      type: string
      label: Machine name of integration
    label:
      type: label
      label: Human-readable name of integration
    settings:
      type: sequence
      label: Integration settings
