netlify.netlify_form:
  path: '/admin/config/services/netlify'
  defaults:
    _form: '\Drupal\netlify\Form\NetlifyForm'
    _title: 'Netlify'
  requirements:
    _permission: 'administer build hook'
