simple_global_filter.global_filter.*:
  type: config_entity
  label: 'Global filter config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    vocabulary_name:
      type: string
      label: 'Vocabulary'
    default_value:
      type: string
      label: 'Default value'
    alias_field:
      type: string
      label: 'Alias field'
