ad_entity.settings.fallback:
  type: mapping
  label: 'Global settings for the Fallback module.'
  mapping:
    timeout:
      type: integer
      label: 'Microseconds to wait until a given fallback will be loaded instead of the original.'

ad_entity.ad_entity.*.third_party_settings.ad_entity_fallback:
  type: mapping
  label: 'Entity config for fallback ads.'
  mapping:
    ad_entity_id:
      type: string
      label: 'The Advertising entity to use as fallback when the current entity is empty.'
