# Schema for the configuration files of the Starter theme.
rocketship_paragraphs.settings:
  type: styling_settings
  label: 'Module settings'
  mapping:
    css_structural:
      type: boolean
      label: 'Structural CSS'
    backgrounds_full:
      type: boolean
      label: 'Full-width backgrounds'
    color_variants:
      type: sequence
      label: 'Color Variants'