id: d7_elfinder_settings
label: Drupal 7 elFinder configuration
migration_tags:
  - Drupal 7
source:
  plugin: variable
  variables:
    - elfinder_settings_filesystem_allowed_extensions
    - elfinder_settings_filesystem_dirperm
    - elfinder_settings_filesystem_fileperm
    - elfinder_settings_filesystem_fileurl
    - elfinder_settings_filesystem_handleprivate
    - elfinder_settings_filesystem_maxfilecount
    - elfinder_settings_filesystem_maxfilesize
    - elfinder_settings_filesystem_mimedetect
    - elfinder_settings_filesystem_owner_format
    - elfinder_settings_filesystem_private_root_label
    - elfinder_settings_filesystem_public_root_label
    - elfinder_settings_filesystem_root_custom
    - elfinder_settings_filesystem_unmanaged_root_label
    - elfinder_settings_filesystem_url_custom
    - elfinder_settings_misc_archivers
    - elfinder_settings_misc_manager_height
    - elfinder_settings_misc_manager_width
    - elfinder_settings_misc_rememberlastdir
    - elfinder_settings_misc_requesttype
    - elfinder_settings_misc_usesystemjquery
    - elfinder_settings_thumbnail_dirname
    - elfinder_settings_thumbnail_imglib
    - elfinder_settings_thumbnail_size
    - elfinder_settings_thumbnail_tmbcrop
process:
  'filesystem/allowed_extensions': elfinder_settings_filesystem_allowed_extensions
  'filesystem/dirperm': elfinder_settings_filesystem_dirperm
  'filesystem/fileperm': elfinder_settings_filesystem_fileperm
  'filesystem/fileurl': elfinder_settings_filesystem_fileurl
  'filesystem/handleprivate': elfinder_settings_filesystem_handleprivate
  'filesystem/maxfilecount': elfinder_settings_filesystem_maxfilecount
  'filesystem/maxfilesize': elfinder_settings_filesystem_maxfilesize
  'filesystem/mimedetect': elfinder_settings_filesystem_mimedetect
  'filesystem/owner_format': elfinder_settings_filesystem_owner_format
  'filesystem/private_root_label': elfinder_settings_filesystem_private_root_label
  'filesystem/public_root_label': elfinder_settings_filesystem_public_root_label
  'filesystem/root_custom': elfinder_settings_filesystem_root_custom
  'filesystem/unmanaged_root_label': elfinder_settings_filesystem_unmanaged_root_label
  'filesystem/url_custom': elfinder_settings_filesystem_url_custom
  'misc/archivers': elfinder_settings_misc_archivers
  'misc/manager_height': elfinder_settings_misc_manager_height
  'misc/manager_width': elfinder_settings_misc_manager_width
  'misc/rememberlastdir': elfinder_settings_misc_rememberlastdir
  'misc/requesttype': elfinder_settings_misc_requesttype
  'misc/usesystemjquery': elfinder_settings_misc_usesystemjquery
  'thumbnail/dirname': elfinder_settings_thumbnail_dirname
  'thumbnail/imglib': elfinder_settings_thumbnail_imglib
  'thumbnail/size': elfinder_settings_thumbnail_size
  'thumbnail/tmbcrop': elfinder_settings_thumbnail_tmbcrop
destination:
  plugin: config
  config_name: elfinder.settings
