domain_registration.settings:
  type: config_object
  label: Settings
  mapping:
    method:
      type: integer
    pattern:
      type: string
    message:
      type: string
    langcode:
      type: string
