entity_graph_usage.settings:
  type: config_object
  mapping:
    entity_types:
      label: Enabled entity types
      type: sequence
      sequence:
        type: sequence
        sequence:
          type: string
