new_relic_rpm.settings:
  type: mapping
  label: Settings
  mapping:
    track_drush:
      type: string
    track_cron:
      type: string
    module_deployment:
      type: boolean
    config_import:
      type: boolean
    ignore_roles:
      type: sequence
      sequence:
        type: string
    ignore_urls:
      type: string
    bg_urls:
      type: string
    exclusive_urls:
      type: string
    api_key:
      type: string
    override_exception_handler:
      type: boolean
    watchdog_severities:
      type: sequence
      sequence:
        type: int
    views_log_slow:
      type: boolean
      label: Log slow views
    views_log_threshold:
      type: int
      label: Slow view threshold in ms
