balance_tracker.settings:
  type: mapping
  label: Settings
  mapping:
    show_in_profile:
      type: boolean
      description: 'Show in profile'
    currency_symbol:
      type: string
      description: 'Currency symbol'
    currency_symbol_position:
      type: string
      description: 'Symbol position'
    thousands_separator:
      type: string
      description: 'Thousands separator'
    decimal_separator:
      type: string
      description: 'Decimal separator'
    custom_date_format:
      type: string
      description: 'Custom date format'
    date_format:
      type: string
      description: 'Date format'
