entity_list.entity_list.*:
  type: config_entity
  label: 'Entity list config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    query:
      type: mapping
      label: 'Query settings'
    display:
      type: mapping
      label: 'Display settings'
    filter:
      type: mapping
      label: 'Filter settings'