image: derh4nnes/pipeline-behat:latest
clone:
  depth: full

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - composer
        script:
          - apt-get update
          - apt-get install -y screen php7.1-sqlite libsqlite3-dev sqlite3
          - export PATH="$HOME/.composer/vendor/bin:$PATH"
          - cd ..
          - mkdir permissions_by_term_redirect/
          - mv build/* permissions_by_term_redirect/
          - mv permissions_by_term_redirect/ build/
          - cd build
          - composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction
          - (cd drupal && composer require behat/behat:^3.0 behat/mink-extension:^2.2 drupal/drupal-extension:^3.2 drupal/permissions_by_term --dev)
          - mv permissions_by_term_redirect drupal/web/modules/contrib
          - (cd drupal/web && ../vendor/drush/drush/drush si standard --db-url=sqlite://sites/default/files/db.sqlite -y && ../vendor/drush/drush/drush en permissions_by_term_redirect -y)
          - (cd drupal && cp web/modules/contrib/permissions_by_term_redirect/tests/src/Behat/composer-require-namespace.php . && php composer-require-namespace.php && composer dump-autoload)
          - (cd drupal && cat composer.json)
          - screen -dmS php-server php -S localhost:8000 -t ./drupal/web
          - (cd drupal/web && cp modules/contrib/permissions_by_term_redirect/tests/src/Behat/behat.yml.dist behat.yml && ../vendor/bin/behat)
        services:
          - testing
    - step:
        name: Deploy
        script:
          - apt-get update && apt-get install -y unzip git
          - git remote add drupal marcoliver@git.drupal.org:project/permissions_by_term_redirect.git
          - git config --global push.default simple
          - git config --global user.name "Marc-Oliver Teschke"
          - git push -u drupal
          - git push --tags
definitions:
  services:
    testing:
      image: darksolar/selenium-chrome-headless
