commerce_payment.commerce_payment_gateway.plugin.braintree_hostedfields:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    public_key:
      type: string
      label: 'Public key'
    private_key:
      type: string
      label: 'Private key'
    merchant_account_id:
      type: sequence
      label: 'Merchant account ID'
      sequence:
        type: string
