# Schema for the configuration files of the Viewport module.

viewport.settings:
  type: config_object
  label: 'Viewport settings'
  mapping:
    selected_pages:
      type: text
      label: 'Selected pages'
    width:
      type: string
      label: 'Viewport width'
    height:
      type: string
      label: 'Viewport height'
    initial_scale:
      type: float
      label: 'Initial scale'
    minimum_scale:
      type: float
      label: 'Minimum scale'
    maximum_scale:
      type: float
      label: 'Maximum scale'
    user_scalable:
      type: boolean
      label: 'User scalable'
