block.settings.facebook_album:
  type: block_settings
  label: 'Facebook Album block settings'
  mapping:
    page_id:
      type: string
      label: 'Page id'
    album_visibility:
      type: integer
      label: 'Album visibility'
    albums:
      type: sequence
      label: 'Albums'
      sequence:
        type: 'string'
        label: 'Album'
    album_limit:
      type: integer
      label: 'Album Limit'
    show_title:
      type: boolean
      label: 'Show title'
    show_description:
      type: boolean
      label: 'Show description'
    show_location:
      type: boolean
      label: 'Show location'
    album_thumb_width:
      type: integer
      label: 'Album thumbnail width'
    album_thumb_height:
      type: integer
      label: 'Album thumbnail height'
    thumb_width:
      type: integer
      label: 'Thumbnail width'
    thumb_height:
      type: integer
      label: 'Thumbnail height'
    colorbox_options:
      type: text
      label: 'Colorbox options'
