# config/schema/commerce_ifthenpay.schema.yml
commerce_payment.commerce_payment_gateway.plugin.ifthenpay:
  type: commerce_payment_gateway_configuration
  mapping:
    multibanco_entidade:
      type: string
      label: 'Multibanco - Entidade'
    multibanco_subentidade:
      type: string
      label: 'Multibanco - Subentidade'
    multibanco_chaveAntiPhishing:
      type: string
      label: 'Chave AntiPhishing'