# Schema for the configuration files of the email confirmer module.

email_confirmer.settings:
  type: config_object
  label: 'Email confirmer settings'
  mapping:
    hash_expiration:
      type: integer
      label: 'Hash expiration'
    restrict_same_ip:
      type: boolean
      label: 'Restrict same IP'
    resendrequest_delay:
      type: integer
      label: 'Request resend delay'
    confirmation_lifetime:
      type: integer
      label: 'Confirmation life time'
    confirmation_request:
      type: mail
      label: 'Confirmation request mail'
    confirmation_response:
      type: mapping
      label: 'Confirmation response'
      mapping:
        questions:
          type: mapping
          label: 'Questions'
          mapping:
            pending:
              type: label
              label: 'Pending'
            expired:
              type: label
              label: 'Expired'
            cancelled:
              type: label
              label: 'Cancelled'
            confirmed:
              type: label
              label: 'Confirmed'
        url:
          type: mapping
          label: 'URLs'
          mapping:
            confirm:
              type: string
              label: 'Confirm'
            cancel:
              type: string
              label: 'Cancel'
            error:
              type: string
              label: 'Error'
