sudo: false

language: php

php:
  - 7.2
  - 7.3

env:
  - MAKE_FILE=drupal-8.6.x.make.yml
  - MAKE_FILE=drupal-8.5.x.make.yml
  - MAKE_FILE=drupal-8.7.x.make.yml

services:
  - mysql

addons:
  apt:
    packages:
    - nginx

notifications:
  slack: det:YiOiwfzUBtt9aTnWvocK8uDI

cache:
  directories:
  - $HOME/.drush/cache/download

before_install:
  - cp $TRAVIS_BUILD_DIR/.travis/php.ini ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/
  - cp $TRAVIS_BUILD_DIR/.travis/php-fpm.conf ~/.phpenv/versions/$(phpenv version-name)/etc/
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - nginx -c $TRAVIS_BUILD_DIR/.travis/nginx.conf
  - wget -P ~/ https://github.com/drush-ops/drush/releases/download/8.2.3/drush.phar && chmod +x ~/drush.phar
  - php ~/drush.phar make $TRAVIS_BUILD_DIR/.travis/$MAKE_FILE $HOME/www
  - php ~/drush.phar --root=$HOME/www --yes site-install --account-pass=admin --db-url=mysql://root:@127.0.0.1/drupal0 testing
  - composer --working-dir=$HOME/www run-script drupal-phpunit-upgrade

install:
  - ln -s $TRAVIS_BUILD_DIR ~/www/modules/deploy
  - php ~/drush.phar --root=$HOME/www --yes --uri=http://localhost:8080 en deploy

script:
  - cd ~/www && php ./core/scripts/run-tests.sh --suppress-deprecations --verbose --keep-results --color --concurrency 4 --php `which php` --sqlite /tmp/test.sqlite --url http://localhost:8080 --module deploy | tee /tmp/test.log ; export STATUS_SCRIPT=${PIPESTATUS[0]}
  - cat /tmp/access8080.log
  - cat /tmp/error8080.log
  # Workaround so that we exit with the correct status.
  - STATUS_LOG=$(! egrep -i "([0-9]+ fails)|([0-9]+ exceptions)|(PHP Fatal error)|(FATAL)" /tmp/test.log > /dev/null)$?
  - test $STATUS_SCRIPT -eq 0 && test $STATUS_LOG -eq 0
