# Replication routing definition
entity.replication.collection:
  path: '/admin/structure/deployment'
  defaults:
    _entity_list: 'replication'
    _title: 'Deployments'
  requirements:
    _permission: 'administer deployments'
  options:
    _admin_route: TRUE

entity.replication.add_form:
  path: '/admin/structure/deployment/add'
  defaults:
    _entity_form: replication.add
    _title_callback: '\Drupal\deploy\Entity\Form\ReplicationForm::addTitle'
  requirements:
    _entity_create_access: 'replication'
  options:
    _admin_route: TRUE
    no_cache: TRUE

entity.replication.view_fail_info:
  path: '/admin/structure/deployment/{replication_id}/fail-info'
  defaults:
    _title_callback: '\Drupal\deploy\Controller\ReplicationFailInfoController::viewTitle'
    _controller: '\Drupal\deploy\Controller\ReplicationFailInfoController::viewFailInfo'
  requirements:
    _permission: 'administer deployments'
  options:
    _admin_route: TRUE
