# @file
# .travis.yml - Drupal 8 Travis CI Integration

language: php

sudo: false

php:
  - 5.6
  - 7

env:
  global:
    - MODULE_NAME='commander'
    - PHPCS_VERSION='2.7.*'
    - CODER_VERSION='8.2.9'

notifications:
  slack: 'xxx'

# Cache Composer & Drush directories.
cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini

  # Composer.
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc
  # - composer self-update

  # Drush.
  - composer global require drush/drush:~8.1

  # Codesniffer.
  - composer global require squizlabs/php_codesniffer:$PHPCS_VERSION

  # Coder.
  - composer global require drupal/coder:$CODER_VERSION
  - ln -s ~/.composer/vendor/drupal/coder/coder_sniffer/Drupal ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/

  # Ensure the PHP environment is ready.
  - phpenv rehash

install:
  - composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction
  - cd drupal && composer install && cd -
  - mkdir -p drupal/web/modules/contrib/$MODULE_NAME

  # switched to doing it this way because it makes local testing a bit easier.
  # create symbolic links to all of the files/folders in the module directory
  - for d in $(pwd)/*; do ln -s "$d" "drupal/web/modules/contrib/$MODULE_NAME"; done

  # remove the recursive drupal folder from the symlinks
  - rm -f drupal/web/modules/contrib/$MODULE_NAME/drupal

  - cd drupal/web

before_script:

  # This fixes a fail when install Drupal.
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Mysql might time out for long tests, increase the wait timeout.
  - mysql -e 'SET @@GLOBAL.wait_timeout=1200'

  # Install Drupal and enable the required modules (including this one).
  - mysql -e 'create database drupal;'
  - cd $TRAVIS_BUILD_DIR/drupal/web && drush --yes site-install standard --db-url="mysql://root@127.0.0.1/drupal"

  # Dependency Modules
  - cd $TRAVIS_BUILD_DIR/drupal/web && drush --yes en $MODULE_NAME

  # Export web server URL for browser tests.
  - export SIMPLETEST_BASE_URL=http://localhost:8080

  # Export database variable for kernel tests.
  - export SIMPLETEST_DB=mysql://root:@127.0.0.1/drupal

script:

  # Start a web server.
  - cd $TRAVIS_BUILD_DIR/drupal/web
  - drush runserver 127.0.0.1:8080 &

  # Run code sniffer.
  # Warnings are disabled until the SMS notifier is ported.
  - phpcs --report=full --standard=Drupal --warning-severity=0 $TRAVIS_BUILD_DIR/drupal/web/modules/contrib/$MODULE_NAME --ignore=bin,*.css,gulpfile.js,libraries,vendor

  # PHP Unit Tests
  - cd $TRAVIS_BUILD_DIR/drupal/web/core
  - ../../vendor/bin/phpunit ../modules/contrib/$MODULE_NAME
