node_paypal_payment.settings:
  type: config_object
  label: 'Node PayPal payment config'
  mapping:
    npp_on:
      type: boolean
      label: 'Allow PayPal payment on node creation'
    npp_email:
      type: email
      label: 'PayPal Email-Id'
    npp_amt:
      type: float
      label: 'Fee'
