services:
  config_log_database_subscriber:
    class: Drupal\config_log\EventSubscriber\ConfigLogDatabaseSubscriber
    arguments: ['@database', '@config.factory']
    tags:
      - { name: event_subscriber }
  config_log_psr_subscriber:
    class: Drupal\config_log\EventSubscriber\ConfigLogPsrSubscriber
    arguments: ['@logger.channel.default', '@config.factory']
    tags:
      - { name: event_subscriber }
  config_log_mail_subscriber:
    class: Drupal\config_log\EventSubscriber\ConfigLogMailSubscriber
    arguments: ['@plugin.manager.mail', '@config.factory', '@language_manager']
    tags:
      - { name: event_subscriber }
