autoban.autoban.*:
  type: mapping
  label: 'Autoban'
  mapping:
    id:
      type: string
      label: 'Autoban rule id'
    uuid:
      type: string
      label: 'UUID'
    type:
      type: string
      label: 'Type of log message, for example page not found.'
    message:
      type: string
      label: 'Pattern of log message.'
    referer:
      type: string
      label: 'Pattern of URL of referring page.'
    threshold:
      type: int
      label: 'The threshold number of the log entries.'
    provider:
      type: string
      label: 'IP ban provider.'
    user_type:
      type: int
      label: 'User type: anonymous, authenticated or any.'
