name: 'Config Merge Filter'
type: module
description: "Provides a Config Filter plugin that safely merges configuration updates into the site's active configuration."
# core: 8.x
package: Config
dependencies:
 - config_merge:config_merge

# Information added by Drupal.org packaging script on 2018-06-05
version: '8.x-1.0-alpha2'
core: '8.x'
project: 'config_merge'
datestamp: 1528237084
