ckeditorheight.settings:
  type: config_object
  label: 'CKEditorHeight settings'
  mapping:
    offset:
      type: float
      label: 'Offset'
    line_height:
      type: float
      label: 'Line height'
    unit:
      type: string
      label: 'Unit'
