name: 'Config Merge'
type: module
description: 'Enables three-way merges of configuration items. This is useful for safely merging configuration updates while retaining any customizations.'
# core: 8.x
package: Config

# Information added by Drupal.org packaging script on 2018-06-05
version: '8.x-1.0-alpha2'
core: '8.x'
project: 'config_merge'
datestamp: 1528237084
