dist: xenial
sudo: required

language: php

cache:
  directories:
    - $HOME/.composer/cache

stages:
  - prepare cache
  - lint
  - phpcs
  - dynamic checks

env:
  global:
    - COMPOSER_BIN_DIR=/home/travis/.config/composer/bin

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3

services:
  - docker

before_install:
  # Pre-validate the composer.json file.
  - composer validate
  # Speed up the build.
  - composer global require hirak/prestissimo
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  # Add phpcs.xml.
  - cp phpcs.dist.xml phpcs.xml
  # Make sure there are no script permission issues.
  - sudo chmod +x .travis-ci -R

jobs:
  include:
    - stage: prepare cache
      script: true
      php: 7.2

    - &lint-defaults
      stage: lint
      php: 5.6
      install: .travis-ci/install-global-linter-packages.sh
      script: ${COMPOSER_BIN_DIR}/parallel-lint .

    - <<: *lint-defaults
      php: 7.0

    - <<: *lint-defaults
      php: 7.1

    - <<: *lint-defaults
      php: 7.2

    - <<: *lint-defaults
      php: 7.3

    - stage: phpcs
      php: 7.2
      install: .travis-ci/install-global-phpcs-packages.sh
      script:
        - ${COMPOSER_BIN_DIR}/phpcs --standard=phpcs.xml .

    # @todo: Currently only runs on php7.2 as the used docker image is 7.2 as well.
    # @todo: Update, so docker image tags can be set dynamically.
    # Job/Stage for dynamic checks, e.g PHPUnit.
    - stage: dynamic checks
      env:
        - TEST_SITE_DIR=docker
      php: 7.2
      install:
        - .travis-ci/create-project.sh
        - .travis-ci/install-docker-site.sh
      script:
        - .travis-ci/start-dynamic-tests.sh

notifications:
  email:
    on_failure: change
    on_success: change
