block.settings.floating_menu_block:
  type: block_settings
  mapping:
    menu_item:
      type: sequence
      label: 'Menu Item'
      sequence:
        type: mapping
        label: 'Menu Item'
        mapping:
          menu_item_popup_html:
            type: text_format
            label: 'Menu Item Popup HTML'
          menu_item_target_url:
            type: string
            label: 'Menu Item Target URL'
          menu_item_icon_file_id:
            type: integer
            label: 'Menu Item File ID'
          menu_item_icon_url:
            type: string
            label: 'Menu Item Icon URL'
