social_auth_unsplash.settings:
  type: config_object
  label: 'Social Auth Unsplash settings'
  mapping:
    client_id:
      type: string
      label: 'Access Key'
    client_secret:
      type: string
      label: 'Secret key'
    scopes:
      type: string
      label: 'Scopes to be requested'
    endpoints:
      type: string
      label: 'API endpoints to be requested'
