# Schema for the configuration of the Pbf field type.
field.storage_settings.protected_file:
  type: base_entity_reference_field_settings
  label: 'File settings'
  mapping:
    display_field:
      type: boolean
      label: 'Enable Display field'
    display_default:
      type: boolean
      label: 'Files displayed by default'
    uri_scheme:
      type: string
      label: 'Upload destination'

field.value.protected_file:
  type: mapping
  label: 'Default value'

base_protected_file_field_field_settings:
  type: mapping
  mapping:
    handler:
      type: string
      label: 'Reference method'
    handler_settings:
      type: entity_reference_selection.[%parent.handler]
      label: 'Entity reference selection settings'
    file_directory:
      type: string
      label: 'File directory'
    file_extensions:
      type: string
      label: 'Allowed file extensions'
    max_filesize:
      type: string
      label: 'Maximum upload size'

field.field_settings.protected_file:
  type: base_protected_file_field_field_settings
  label: 'Protected File settings'
  mapping:
    description_field:
      type: boolean
      label: 'Enable Description field'

field.formatter.settings.protected_file_formatter:
  type: mapping
  label: 'Generic protected file format settings'
  mapping:
    protected_file_new_window:
      type: boolean
      label: 'Open file in new tab'
    protected_file_path:
      type: string
      label: 'The redirect path'
    redirect_to_file:
      type: boolean
      label: 'Redirect directly to private file after login'
    protected_file_modal:
      type: boolean
      label: 'Open redirect path in a modal'
    protected_file_message:
      type: string
      label: 'The link protected title attibute'

field.widget.settings.protected_file_widget:
  type: mapping
  label: 'Protected File format settings'
  mapping:
    progress_indicator:
      type: string
      label: 'Progress indicator'
