# Schema for the configuration files of the uc_quickpay module.
payment_method.settings.quickpay_gateway:
  type: mapping
  label: 'Quickpay credit card configuration settings'
  mapping:
    merchant_id:
      type: integer
      label: 'Merchant ID'
    user_api_key:
      type: string
      label: 'API user key'
    agreement_id:
      type: integer
      label: 'Agreement ID'
    payment_api_key:
      type: string
      label: 'Payment Window API key'
    pre_order_id:
      type: integer
      label: 'Order id prefix'
    continue_url:
      type: string
      label: 'Continue URL'
    cancel_url:
      type: string
      label: 'Cancel URL'
    3d_secure:
      type: boolean
      label: 'Select 3d_secure'

payment_method.settings.quickpay_form_gateway:
  type: mapping
  label: 'Quickpay form configuration settings'
  mapping:
    merchant_id:
      type: integer
      label: 'Merchant ID'
    private_key:
      type: string
      label: 'Private Key'
    agreement_id:
      type: integer
      label: 'Agreement ID'
    payment_api_key:
      type: string
      label: 'Payment Window API key'
    pre_order_id:
      type: integer
      label: 'Order id prefix'
    language:
      type: string
      label: 'Payment Language'
    payment_method:
      type: sequences 
      label: 'Payment Methods'
    autofee:
      type: boolean
      label: 'Autofee'
    autocapture:
      type: boolean
      label: 'Autocapture'
