fillpdf.settings:
  type: config_object
  mapping:
    backend:
      type: string
      label: 'PDF processing method'
    remote_protocol:
      type: string
      label: 'FillPDF Service endpoint protocol'
    remote_endpoint:
      type: string
      label: 'FillPDF Service endpoint URL without protocol'
    allowed_schemes:
      type: sequence
      label: 'Allowed storage schemes'
      sequence:
        type: string
        label: 'Allowed storage scheme'
    template_scheme:
      type: string
      label: 'Template storage scheme'
    local_service_endpoint:
      type: string
      label: 'Local FillPDF PDF API endpoint'
